/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 lion.gltf 
Author: matousekfoto (https://sketchfab.com/matousekfoto)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lion-door-knocker-36d3c4f4b9454f4d9aaf5aab892586ca
Title: Lion door knocker
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/lion.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-32.568, -70.935, -77.051]}
        rotation={[0.083, -0.04, -0.452]}
        scale={0}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.meshNode_Material_u1_v1_0.geometry}
            material={materials.Material_u1_v1}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/lion.gltf");
