import test from "../../assets/audio/test.mp3";
import SPD1K01 from "../../assets/audio/SPD1K01.m4a";
import SPD1K02 from "../../assets/audio/SPD1K02.m4a";
import SPD1K03 from "../../assets/audio/SPD1K03.m4a";
import furcht from "../../assets/images/furcht_sketch.jpg";

import prev from "../../assets/images/spk_prev.jpg";

export const chapters = [
  {
    id: "spk363636",
    chapter: 1,
    title: "chapter 1",
    src: SPD1K01,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spkBF3030",
    chapter: 2,
    title: "chapter 2",
    src: SPD1K02,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spkD10A0A",
    chapter: 3,
    title: "chapter 3",
    src: SPD1K03,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spkFF8929",
    chapter: 4,
    title: "chapter 4",
    src: test,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spkFFB229",
    chapter: 5,
    title: "chapter 5",
    src: test,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spkFFD929",
    chapter: 6,
    title: "chapter 6",
    src: test,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spkFFFB29",
    chapter: 7,
    title: "chapter 7",
    src: test,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spkAAE352",
    chapter: 8,
    title: "chapter 8",
    src: test,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spk61C35C",
    chapter: 9,
    title: "chapter 9",
    src: test,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spk58DAA0",
    chapter: 10,
    title: "chapter 10",
    src: test,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spk58D0DA",
    chapter: 11,
    title: "chapter 11",
    src: test,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spk6694EF",
    chapter: 12,
    title: "chapter 12",
    src: test,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spk8166EF",
    chapter: 13,
    title: "chapter 13",
    src: test,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spkC566EF",
    chapter: 14,
    title: "chapter 14",
    src: test,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spkFF60BF",
    chapter: 15,
    title: "chapter 15",
    src: test,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spkFF6083",
    chapter: 16,
    title: "chapter 16",
    src: test,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
  {
    id: "spkFFFFFF",
    chapter: 17,
    title: "chapter 17",
    src: test,
    img: furcht,
    imgPreview: prev,
    alt: "furcht",
  },
];
