import test from "../../assets/audio/test.mp3";
import furcht from "../../assets/images/furcht_sketch.jpg";

export const chapters = [
  {
    id: "spkliao",
    chapter: 1,
    title: "chapter 1",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spkhbls",
    chapter: 2,
    title: "chapter 2",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spkgg7x",
    chapter: 3,
    title: "chapter 3",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spkgw4e",
    chapter: 4,
    title: "chapter 4",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spk1e47",
    chapter: 5,
    title: "chapter 5",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spkpgfa",
    chapter: 6,
    title: "chapter 6",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spknl1g",
    chapter: 7,
    title: "chapter 7",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spkx1y6",
    chapter: 8,
    title: "chapter 8",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spk9jyz",
    chapter: 9,
    title: "chapter 9",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spk5c8t",
    chapter: 10,
    title: "chapter 10",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spk4hv8",
    chapter: 11,
    title: "chapter 11",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spk4xjp",
    chapter: 12,
    title: "chapter 12",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spkporh",
    chapter: 13,
    title: "chapter 13",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spkch2b",
    chapter: 14,
    title: "chapter 14",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spkbmoq",
    chapter: 15,
    title: "chapter 15",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spkl2c7",
    chapter: 16,
    title: "chapter 16",
    src: test,
    img: furcht,
    alt: "furcht",
  },
  {
    id: "spkwkl0",
    chapter: 17,
    title: "chapter 17",
    src: test,
    img: furcht,
    alt: "furcht",
  },
];
